theme: jekyll-theme-minimal
title: [Plataforma META POT]
description: [A short description of your site's purpose]
logo: [https://github.com/wmpjrufg/META_PYTHON_OPTIMIZATION_TOOLBOX/blob/gh-pages/logo01.png]
